fix deployment after using nginx

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -42,6 +42,7 @@ jobs:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
+          command_timeout: 10m
           script: |
             sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
 
@@ -56,7 +57,23 @@ jobs:
 
             sudo docker ps
 
-            curl -f http://127.0.0.1:5000 || exit 1
+            echo "Waiting for Flask app to start..."
+
+            for i in {1..10}; do
+              if curl -fsS http://127.0.0.1:5000; then
+                echo "Flask app is running successfully"
+                break
+              fi
+
+              echo "App not ready yet. Retrying in 5 seconds..."
+              sleep 5
+
+              if [ "$i" -eq 10 ]; then
+                echo "App health check failed. Showing Docker logs:"
+                sudo docker logs ${{ env.CONTAINER_NAME }}
+                exit 1
+              fi
+            done
 
             sudo nginx -t
             sudo systemctl reload nginx
